In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw dataset
df = pd.read_csv("military_raw_data.csv")

# Display first 5 rows
df.head()

,country_id,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,power_index_rank,power_index_score,continent,region,gdp_usd,alliance
0,1,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,529",...,"9,596,960 km","14,500 km","22,457 km","27,700 km",3,NaN,Asia,Eastern Asia,1.800000e+13,NaN
1,2,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,431,000","1,000,000","2,527,000","2,183",...,"3,287,263 km","7,000 km","13,888 km","14,500 km",4,NaN,Asia,Southern Asia,3.390000e+12,NaN
2,3,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,333,030","799,500",0,"13,032",...,"9,833,517 km","19,924 km","12,002 km","41,009 km",1,NaN,Americas,Northern America,2.550000e+13,NATO
3,4,Indonesia,"281,562,465","137,965,608","114,595,923","4,786,562","404,500","401,000","250,000",460,...,"1,904,569 km","54,716 km","2,958 km","21,579 km",13,NaN,Asia,South-eastern Asia,1.320000e+12,NaN
4,5,Pakistan,"252,363,571","108,516,336","85,803,614","4,794,908","660,000","550,000","500,000","1,397",...,"796,095 km","1,046 km","7,257 km",0 km,14,NaN,Asia,Southern Asia,3.770000e+11,NaN

 Validate the Raw Dataset

In [3]:
# Shape of dataset
print("Shape of dataset:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)

# Data types
print("\nData Types:")
print(df.dtypes)

# General information
print("\nDataset Info:")
df.info()

Shape of dataset: (145, 62)

Column Names:
Index(['country_id', 'country', 'total_population', 'total_military_manpower',
       'fit_for_service', 'population_reaching_military_age_annually',
       'active_personnel', 'reserve_personnel', 'paramilitary',
       'total_military_aircraft', 'fighter_aircraft', 'attack_aircraft',
       'transport_aircraft', 'trainer_aircraft', 'special_mission_aircraft',
       'tanker_aircraft', 'total_military_helicopters', 'attack_helicopters',
       'tanks', 'armored_fighting_vehicles', 'self_propelled_artillery',
       'towed_artillery', 'rocket_projectors', 'total_naval_fleet',
       'total_naval_fleet_tonnage_mt', 'aircraft_carriers',
       'helicopter_carriers', 'submarines', 'destroyers', 'frigates',
       'corvettes', 'coastal_patrol_craft', 'mine_warfare_craft',
       'defense_budget_usd', 'external_debt_usd',
       'purchasing_power_parity_usd', 'foreign_exchange_and_gold_reserves_usd',
       'total_serviceable_airports', 'labour_force',
       'major_ports_and_terminals', 'total_merchant_marine_fleet',
       'railway_coverage_km', 'roadway_coverage_km', 'oil_production_bbl',
       'oil_consumption_bbl', 'proven_oil_reserves_bbl',
       'natural_gas_production_cum', 'natural_gas_consumption_cum',
       'proven_natural_gas_reserves_cum', 'coal_production_cum',
       'coal_consumption_mt', 'proven_coal_reserves_cum',
       'total_land_area_sq_km', 'coastline_coverage_km', 'border_coverage_km',
       'waterway_coverage_km', 'power_index_rank', 'power_index_score',
       'continent', 'region', 'gdp_usd', 'alliance'],
      dtype='object')

Data Types:
country_id                   int64
country                     object
total_population            object
total_military_manpower     object
fit_for_service             object
                            ...
power_index_score          float64
continent                   object
region                      object
gdp_usd                    float64
alliance                    object
Length: 62, dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 62 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country_id                                 145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    object
 3   total_military_manpower                    145 non-null    object
 4   fit_for_service                            145 non-null    object
 5   population_reaching_military_age_annually  145 non-null    object
 6   active_personnel                           145 non-null    object
 7   reserve_personnel                          145 non-null    object
 8   paramilitary                               145 non-null    object
 9   total_military_aircraft                    145 non-null    object
 10  fighter_aircraft                           145 non-null    object
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    object
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    object
 17  attack_helicopters                         145 non-null    object
 18  tanks                                      145 non-null    object
 19  armored_fighting_vehicles                  145 non-null    object
 20  self_propelled_artillery                   145 non-null    object
 21  towed_artillery                            145 non-null    object
 22  rocket_projectors                          145 non-null    object
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               51 non-null     object
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         145 non-null    object
 34  external_debt_usd                          145 non-null    object
 35  purchasing_power_parity_usd                145 non-null    object
 36  foreign_exchange_and_gold_reserves_usd     145 non-null    object
 37  total_serviceable_airports                 145 non-null    object
 38  labour_force                               145 non-null    object
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    object
 41  railway_coverage_km                        145 non-null    object
 42  roadway_coverage_km                        145 non-null    object
 43  oil_production_bbl                         145 non-null    object
 44  oil_consumption_bbl                        145 non-null    object
 45  proven_oil_reserves_bbl                    145 non-null    object
 46  natural_gas_production_cum                 145 non-null    object
 47  natural_gas_consumption_cum                145 non-null    object
 48  proven_natural_gas_reserves_cum            145 non-null    object
 49  coal_production_cum                        145 non-null    object
 50  coal_consumption_mt                        145 non-null    object
 51  proven_coal_reserves_cum                   145 non-null    object
 52  total_land_area_sq_km                      145 non-null    object
 53  coastline_coverage_km                      145 non-null    object
 54  border_coverage_km                         145 non-null    object
 55  waterway_coverage_km                       145 non-null    object
 56  power_index_rank                           145 non-null    int64
 57  power_index_score                          0 non-null      float64
 58  continent                                  135 non-null    object
 59  region                                     135 non-null    object
 60  gdp_usd                                    129 non-null    float64
 61  alliance                                   30 non-null     object
dtypes: float64(2), int64(16), object(44)
memory usage: 70.4+ KB

Check Missing Values

In [4]:
# Missing values
print("Missing Values:")
print(df.isnull().sum())

# Missing values percentage
missing_percent = (df.isnull().sum() / len(df)) * 100

print("\nMissing Percentage:")
print(missing_percent.sort_values(ascending=False))

Missing Values:
country_id                   0
country                      0
total_population             0
total_military_manpower      0
fit_for_service              0
                          ...
power_index_score          145
continent                   10
region                      10
gdp_usd                     16
alliance                   115
Length: 62, dtype: int64

Missing Percentage:
power_index_score               100.000000
alliance                         79.310345
total_naval_fleet_tonnage_mt     64.827586
gdp_usd                          11.034483
region                            6.896552
                                   ...
helicopter_carriers               0.000000
submarines                        0.000000
destroyers                        0.000000
frigates                          0.000000
coastal_patrol_craft              0.000000
Length: 62, dtype: float64

Check Duplicate Rows

In [5]:
# Duplicate rows
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

Check Sample Data

In [6]:
# First 10 rows
df.head(10)

,country_id,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,power_index_rank,power_index_score,continent,region,gdp_usd,alliance
0,1,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,529",...,"9,596,960 km","14,500 km","22,457 km","27,700 km",3,NaN,Asia,Eastern Asia,1.800000e+13,NaN
1,2,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,431,000","1,000,000","2,527,000","2,183",...,"3,287,263 km","7,000 km","13,888 km","14,500 km",4,NaN,Asia,Southern Asia,3.390000e+12,NaN
2,3,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,333,030","799,500",0,"13,032",...,"9,833,517 km","19,924 km","12,002 km","41,009 km",1,NaN,Americas,Northern America,2.550000e+13,NATO
3,4,Indonesia,"281,562,465","137,965,608","114,595,923","4,786,562","404,500","401,000","250,000",460,...,"1,904,569 km","54,716 km","2,958 km","21,579 km",13,NaN,Asia,South-eastern Asia,1.320000e+12,NaN
4,5,Pakistan,"252,363,571","108,516,336","85,803,614","4,794,908","660,000","550,000","500,000","1,397",...,"796,095 km","1,046 km","7,257 km",0 km,14,NaN,Asia,Southern Asia,3.770000e+11,NaN
5,6,Nigeria,"236,747,130","125,475,979","90,437,404","4,261,448","230,000",0,"50,000",159,...,"923,768 km",853 km,"4,477 km","8,600 km",33,NaN,Africa,Sub-Saharan Africa,4.770000e+11,NaN
6,7,Brazil,"220,051,512","112,226,271","88,680,759","3,520,824","376,000","1,340,000","200,000",495,...,"8,515,770 km","7,491 km","16,145 km","50,000 km",11,NaN,Americas,Latin America and the Caribbean,1.920000e+12,NaN
7,8,Bangladesh,"168,697,184","82,661,620","66,129,296","3,205,246","204,000",0,"6,800,000",212,...,"148,460 km",580 km,"4,413 km","8,370 km",37,NaN,Asia,Southern Asia,4.600000e+11,NaN
8,9,Russia,"140,820,810","69,002,197","46,189,226","1,267,387","1,320,000","2,000,000","250,000","4,237",...,"17,098,242 km","37,653 km","22,407 km","102,000 km",2,NaN,Europe,Eastern Europe,NaN,NaN
9,10,Mexico,"130,739,927","61,447,766","49,811,912","2,222,579","387,000","98,653","120,000",424,...,"1,964,375 km","9,330 km","4,389 km","2,900 km",36,NaN,Americas,Latin America and the Caribbean,1.410000e+12,NaN

Create a Copy of Raw Dataset

In [7]:
# Create a copy of raw dataset
clean_df = df.copy()

print("Copy created successfully!")

Copy created successfully!

Check Data Types

In [8]:
clean_df.dtypes

country_id                   int64
country                     object
total_population            object
total_military_manpower     object
fit_for_service             object
                            ...
power_index_score          float64
continent                   object
region                      object
gdp_usd                    float64
alliance                    object
Length: 62, dtype: object

Check Object Columns

In [9]:
for col in clean_df.select_dtypes(include="object").columns:
    print("\n", "="*60)
    print(col)
    print(clean_df[col].dropna().head())

 ============================================================
country
0            China
1            India
2    United States
3        Indonesia
4         Pakistan
Name: country, dtype: object

 ============================================================
total_population
0    1,415,043,270
1    1,409,128,296
2      341,963,408
3      281,562,465
4      252,363,571
Name: total_population, dtype: object

 ============================================================
total_military_manpower
0    764,123,366
1    662,290,299
2    150,463,900
3    137,965,608
4    108,516,336
Name: total_military_manpower, dtype: object

 ============================================================
fit_for_service
0    626,864,169
1    522,786,598
2    124,816,644
3    114,595,923
4     85,803,614
Name: fit_for_service, dtype: object

 ============================================================
population_reaching_military_age_annually
0    19,810,606
1    23,955,181
2     4,445,524
3     4,786,562
4     4,794,908
Name: population_reaching_military_age_annually, dtype: object

 ============================================================
active_personnel
0    2,035,000
1    1,431,000
2    1,333,030
3      404,500
4      660,000
Name: active_personnel, dtype: object

 ============================================================
reserve_personnel
0      510,000
1    1,000,000
2      799,500
3      401,000
4      550,000
Name: reserve_personnel, dtype: object

 ============================================================
paramilitary
0      625,000
1    2,527,000
2            0
3      250,000
4      500,000
Name: paramilitary, dtype: object

 ============================================================
total_military_aircraft
0     3,529
1     2,183
2    13,032
3       460
4     1,397
Name: total_military_aircraft, dtype: object

 ============================================================
fighter_aircraft
0    1,443
1      476
2    1,791
3       41
4      331
Name: fighter_aircraft, dtype: object

 ============================================================
trainer_aircraft
0      401
1      334
2    2,610
3      114
4      563
Name: trainer_aircraft, dtype: object

 ============================================================
total_military_helicopters
0    1,007
1      594
2    5,913
3      212
4      379
Name: total_military_helicopters, dtype: object

 ============================================================
attack_helicopters
0      281
1       79
2    1,024
3       15
4       55
Name: attack_helicopters, dtype: object

 ============================================================
tanks
0    5,870
1    3,913
2    4,666
3      331
4    2,677
Name: tanks, dtype: object

 ============================================================
armored_fighting_vehicles
0    152,040
1    163,554
2    409,660
3     28,064
4     59,044
Name: armored_fighting_vehicles, dtype: object

 ============================================================
self_propelled_artillery
0    2,940
1      100
2    1,521
3      153
4      662
Name: self_propelled_artillery, dtype: object

 ============================================================
towed_artillery
0    1,400
1    5,640
2    1,878
3      396
4    2,629
Name: towed_artillery, dtype: object

 ============================================================
rocket_projectors
0    2,770
1      300
2    1,731
3       67
4      652
Name: rocket_projectors, dtype: object

 ============================================================
total_naval_fleet_tonnage_mt
0    3,192,411
1      631,989
2    8,265,799
3      324,754
4      115,187
Name: total_naval_fleet_tonnage_mt, dtype: object

 ============================================================
defense_budget_usd
0    $ 303,000,000,000
1    $ 109,000,000,000
2    $ 831,500,000,000
3     $ 11,155,297,716
4      $ 9,102,115,350
Name: defense_budget_usd, dtype: object

 ============================================================
external_debt_usd
0       $ 488,114,000,000
1       $ 212,728,000,000
2    $ 24,538,900,710,000
3       $ 225,273,000,000
4        $ 89,148,000,000
Name: external_debt_usd, dtype: object

 ============================================================
purchasing_power_parity_usd
0    $ 33,598,000,000,000
1    $ 14,244,000,000,000
2    $ 25,676,000,000,000
3     $ 4,102,000,000,000
4     $ 1,390,000,000,000
Name: purchasing_power_parity_usd, dtype: object

 ============================================================
foreign_exchange_and_gold_reserves_usd
0    $ 3,456,000,000,000
1      $ 643,043,000,000
2      $ 910,037,000,000
3      $ 155,708,000,000
4       $ 18,408,000,000
Name: foreign_exchange_and_gold_reserves_usd, dtype: object

 ============================================================
total_serviceable_airports
0       552
1       315
2    16,116
3       556
4       117
Name: total_serviceable_airports, dtype: object

 ============================================================
labour_force
0    773,880,000
1    607,691,000
2    174,174,000
3    143,144,000
4     83,644,000
Name: labour_force, dtype: object

 ============================================================
total_merchant_marine_fleet
0     8,314
1     1,859
2     3,533
3    11,422
4        60
Name: total_merchant_marine_fleet, dtype: object

 ============================================================
railway_coverage_km
0    150,000 km
1     65,554 km
2    293,564 km
3      8,159 km
4     11,881 km
Name: railway_coverage_km, dtype: object

 ============================================================
roadway_coverage_km
0    5,200,000 km
1    6,371,847 km
2    6,586,610 km
3      496,607 km
4      264,175 km
Name: roadway_coverage_km, dtype: object

 ============================================================
oil_production_bbl
0     4,984,000 bbl
1       822,000 bbl
2    20,953,000 bbl
3       865,000 bbl
4        91,000 bbl
Name: oil_production_bbl, dtype: object

 ============================================================
oil_consumption_bbl
0    16,189,000 bbl
1     5,271,000 bbl
2    20,307,000 bbl
3     1,645,000 bbl
4       645,000 bbl
Name: oil_consumption_bbl, dtype: object

 ============================================================
proven_oil_reserves_bbl
0    26,023,000,000 bbl
1     4,605,000,000 bbl
2    38,212,000,000 bbl
3     2,480,000,000 bbl
4       540,000,000 bbl
Name: proven_oil_reserves_bbl, dtype: object

 ============================================================
natural_gas_production_cum
0      225,341,000,000 Cu.M
1       33,170,000,000 Cu.M
2    1,029,000,000,000 Cu.M
3       57,410,000,000 Cu.M
4       36,937,000,000 Cu.M
Name: natural_gas_production_cum, dtype: object

 ============================================================
natural_gas_consumption_cum
0    366,160,000,000 Cu.M
1     58,867,000,000 Cu.M
2    914,301,000,000 Cu.M
3     36,061,000,000 Cu.M
4     46,448,000,000 Cu.M
Name: natural_gas_consumption_cum, dtype: object

 ============================================================
proven_natural_gas_reserves_cum
0     6,654,000,000,000 Cu.M
1     1,381,000,000,000 Cu.M
2    13,402,000,000,000 Cu.M
3     1,408,000,000,000 Cu.M
4       592,219,000,000 Cu.M
Name: proven_natural_gas_reserves_cum, dtype: object

 ============================================================
coal_production_cum
0    4,805,000,000 Cu.M
1    1,020,000,000 Cu.M
2      534,234,000 Cu.M
3      783,453,000 Cu.M
4       13,765,000 Cu.M
Name: coal_production_cum, dtype: object

 ============================================================
coal_consumption_mt
0    5,191,000,000 mt
1    1,262,000,000 mt
2      495,156,000 mt
3      281,159,000 mt
4       30,191,000 mt
Name: coal_consumption_mt, dtype: object

 ============================================================
proven_coal_reserves_cum
0    157,041,000,000 Cu.M
1    127,727,000,000 Cu.M
2    247,883,000,000 Cu.M
3     35,055,000,000 Cu.M
4      2,857,000,000 Cu.M
Name: proven_coal_reserves_cum, dtype: object

 ============================================================
total_land_area_sq_km
0    9,596,960 km
1    3,287,263 km
2    9,833,517 km
3    1,904,569 km
4      796,095 km
Name: total_land_area_sq_km, dtype: object

 ============================================================
coastline_coverage_km
0    14,500 km
1     7,000 km
2    19,924 km
3    54,716 km
4     1,046 km
Name: coastline_coverage_km, dtype: object

 ============================================================
border_coverage_km
0    22,457 km
1    13,888 km
2    12,002 km
3     2,958 km
4     7,257 km
Name: border_coverage_km, dtype: object

 ============================================================
waterway_coverage_km
0    27,700 km
1    14,500 km
2    41,009 km
3    21,579 km
4         0 km
Name: waterway_coverage_km, dtype: object

 ============================================================
continent
0        Asia
1        Asia
2    Americas
3        Asia
4        Asia
Name: continent, dtype: object

 ============================================================
region
0          Eastern Asia
1         Southern Asia
2      Northern America
3    South-eastern Asia
4         Southern Asia
Name: region, dtype: object

 ============================================================
alliance
2     NATO
18    NATO
20    NATO
21    NATO
23    NATO
Name: alliance, dtype: object

Clean Numeric Columns

In [10]:
# Keep text columns unchanged
text_columns = ["country", "continent", "region", "alliance"]

# Get object columns except text columns
numeric_object_cols = [
    col for col in clean_df.select_dtypes(include="object").columns
    if col not in text_columns
]

# Remove special characters
for col in numeric_object_cols:
    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("%", "", regex=False)
        .str.replace("+", "", regex=False)
        .str.replace("km", "", regex=False)
        .str.replace("mt", "", regex=False)
        .str.replace("bbl", "", regex=False)
        .str.replace("cum", "", regex=False)
        .str.strip()
    )

print("Special characters removed successfully!")

Special characters removed successfully!

Convert to Numeric

In [11]:
# Convert cleaned columns to numeric
for col in numeric_object_cols:
    clean_df[col] = pd.to_numeric(clean_df[col], errors="coerce")

print("Numeric conversion completed!")

Numeric conversion completed!

Verify

In [12]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 62 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country_id                                 145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    int64
 3   total_military_manpower                    145 non-null    int64
 4   fit_for_service                            145 non-null    int64
 5   population_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                           145 non-null    int64
 7   reserve_personnel                          145 non-null    int64
 8   paramilitary                               145 non-null    int64
 9   total_military_aircraft                    145 non-null    int64
 10  fighter_aircraft                           145 non-null    int64
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    int64
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    int64
 17  attack_helicopters                         145 non-null    int64
 18  tanks                                      145 non-null    int64
 19  armored_fighting_vehicles                  145 non-null    int64
 20  self_propelled_artillery                   145 non-null    int64
 21  towed_artillery                            145 non-null    int64
 22  rocket_projectors                          145 non-null    int64
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               51 non-null     float64
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         0 non-null      float64
 34  external_debt_usd                          0 non-null      float64
 35  purchasing_power_parity_usd                0 non-null      float64
 36  foreign_exchange_and_gold_reserves_usd     0 non-null      float64
 37  total_serviceable_airports                 145 non-null    int64
 38  labour_force                               145 non-null    int64
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    int64
 41  railway_coverage_km                        145 non-null    int64
 42  roadway_coverage_km                        145 non-null    int64
 43  oil_production_bbl                         145 non-null    int64
 44  oil_consumption_bbl                        145 non-null    int64
 45  proven_oil_reserves_bbl                    145 non-null    int64
 46  natural_gas_production_cum                 0 non-null      float64
 47  natural_gas_consumption_cum                0 non-null      float64
 48  proven_natural_gas_reserves_cum            0 non-null      float64
 49  coal_production_cum                        0 non-null      float64
 50  coal_consumption_mt                        145 non-null    int64
 51  proven_coal_reserves_cum                   0 non-null      float64
 52  total_land_area_sq_km                      145 non-null    int64
 53  coastline_coverage_km                      145 non-null    int64
 54  border_coverage_km                         145 non-null    int64
 55  waterway_coverage_km                       145 non-null    int64
 56  power_index_rank                           145 non-null    int64
 57  power_index_score                          0 non-null      float64
 58  continent                                  135 non-null    object
 59  region                                     135 non-null    object
 60  gdp_usd                                    129 non-null    float64
 61  alliance                                   30 non-null     object
dtypes: float64(12), int64(46), object(4)
memory usage: 70.4+ KB

Validate Missing Values

In [13]:
# Missing values after cleaning
missing = clean_df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

defense_budget_usd                        145
external_debt_usd                         145
purchasing_power_parity_usd               145
foreign_exchange_and_gold_reserves_usd    145
natural_gas_production_cum                145
natural_gas_consumption_cum               145
proven_natural_gas_reserves_cum           145
coal_production_cum                       145
proven_coal_reserves_cum                  145
power_index_score                         145
alliance                                  115
total_naval_fleet_tonnage_mt               94
gdp_usd                                    16
continent                                  10
region                                     10
dtype: int64

In [14]:
# Missing percentage
missing_percent = (clean_df.isnull().sum() / len(clean_df)) * 100

missing_percent = missing_percent[missing_percent > 0].sort_values(ascending=False)

print(missing_percent)

defense_budget_usd                        100.000000
external_debt_usd                         100.000000
purchasing_power_parity_usd               100.000000
foreign_exchange_and_gold_reserves_usd    100.000000
natural_gas_production_cum                100.000000
natural_gas_consumption_cum               100.000000
proven_natural_gas_reserves_cum           100.000000
coal_production_cum                       100.000000
proven_coal_reserves_cum                  100.000000
power_index_score                         100.000000
alliance                                   79.310345
total_naval_fleet_tonnage_mt               64.827586
gdp_usd                                    11.034483
continent                                   6.896552
region                                      6.896552
dtype: float64

In [15]:
cols = [
    "defense_budget_usd",
    "external_debt_usd",
    "purchasing_power_parity_usd",
    "foreign_exchange_and_gold_reserves_usd"
]

for col in cols:
    print("\n", "="*60)
    print(col)
    print(df[col].head(10))

 ============================================================
defense_budget_usd
0    $ 303,000,000,000
1    $ 109,000,000,000
2    $ 831,500,000,000
3     $ 11,155,297,716
4      $ 9,102,115,350
5      $ 3,900,000,000
6     $ 26,400,000,000
7      $ 3,340,000,000
8    $ 212,638,272,000
9      $ 9,100,000,000
Name: defense_budget_usd, dtype: object

 ============================================================
external_debt_usd
0       $ 488,114,000,000
1       $ 212,728,000,000
2    $ 24,538,900,710,000
3       $ 225,273,000,000
4        $ 89,148,000,000
5        $ 45,009,000,000
6       $ 198,582,000,000
7        $ 58,020,000,000
8       $ 226,475,750,000
9       $ 306,308,000,000
Name: external_debt_usd, dtype: object

 ============================================================
purchasing_power_parity_usd
0    $ 33,598,000,000,000
1    $ 14,244,000,000,000
2    $ 25,676,000,000,000
3     $ 4,102,000,000,000
4     $ 1,390,000,000,000
5     $ 1,318,000,000,000
6     $ 4,165,000,000,000
7     $ 1,473,000,000,000
8     $ 6,089,000,000,000
9     $ 2,883,000,000,000
Name: purchasing_power_parity_usd, dtype: object

 ============================================================
foreign_exchange_and_gold_reserves_usd
0    $ 3,456,000,000,000
1      $ 643,043,000,000
2      $ 910,037,000,000
3      $ 155,708,000,000
4       $ 18,408,000,000
5       $ 38,612,000,000
6      $ 329,732,000,000
7       $ 21,395,000,000
8      $ 597,217,000,000
9      $ 232,035,000,000
Name: foreign_exchange_and_gold_reserves_usd, dtype: object

In [16]:
# Reload raw dataset
clean_df = pd.read_csv("military_raw_data.csv")

In [17]:
# Text columns
text_columns = ["country", "continent", "region", "alliance"]

numeric_object_cols = [
    col for col in clean_df.select_dtypes(include="object").columns
    if col not in text_columns
]

for col in numeric_object_cols:

    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .str.replace("%", "", regex=False)
        .str.replace("+", "", regex=False)
        .str.replace("km", "", regex=False)
        .str.replace("mt", "", regex=False)
        .str.replace("bbl", "", regex=False)
        .str.replace("cum", "", regex=False)
        .str.strip()
    )

    clean_df[col] = pd.to_numeric(
        clean_df[col],
        errors="coerce"
    )

print("Cleaning completed!")

Cleaning completed!

In [18]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 62 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country_id                                 145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    int64
 3   total_military_manpower                    145 non-null    int64
 4   fit_for_service                            145 non-null    int64
 5   population_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                           145 non-null    int64
 7   reserve_personnel                          145 non-null    int64
 8   paramilitary                               145 non-null    int64
 9   total_military_aircraft                    145 non-null    int64
 10  fighter_aircraft                           145 non-null    int64
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    int64
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    int64
 17  attack_helicopters                         145 non-null    int64
 18  tanks                                      145 non-null    int64
 19  armored_fighting_vehicles                  145 non-null    int64
 20  self_propelled_artillery                   145 non-null    int64
 21  towed_artillery                            145 non-null    int64
 22  rocket_projectors                          145 non-null    int64
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               51 non-null     float64
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         145 non-null    int64
 34  external_debt_usd                          145 non-null    int64
 35  purchasing_power_parity_usd                145 non-null    int64
 36  foreign_exchange_and_gold_reserves_usd     145 non-null    int64
 37  total_serviceable_airports                 145 non-null    int64
 38  labour_force                               145 non-null    int64
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    int64
 41  railway_coverage_km                        145 non-null    int64
 42  roadway_coverage_km                        145 non-null    int64
 43  oil_production_bbl                         145 non-null    int64
 44  oil_consumption_bbl                        145 non-null    int64
 45  proven_oil_reserves_bbl                    145 non-null    int64
 46  natural_gas_production_cum                 0 non-null      float64
 47  natural_gas_consumption_cum                0 non-null      float64
 48  proven_natural_gas_reserves_cum            0 non-null      float64
 49  coal_production_cum                        0 non-null      float64
 50  coal_consumption_mt                        145 non-null    int64
 51  proven_coal_reserves_cum                   0 non-null      float64
 52  total_land_area_sq_km                      145 non-null    int64
 53  coastline_coverage_km                      145 non-null    int64
 54  border_coverage_km                         145 non-null    int64
 55  waterway_coverage_km                       145 non-null    int64
 56  power_index_rank                           145 non-null    int64
 57  power_index_score                          0 non-null      float64
 58  continent                                  135 non-null    object
 59  region                                     135 non-null    object
 60  gdp_usd                                    129 non-null    float64
 61  alliance                                   30 non-null     object
dtypes: float64(8), int64(50), object(4)
memory usage: 70.4+ KB

In [19]:
cols = [
    "natural_gas_production_cum",
    "natural_gas_consumption_cum",
    "proven_natural_gas_reserves_cum",
    "coal_production_cum",
    "proven_coal_reserves_cum"
]

for col in cols:
    print("\n", "="*60)
    print(col)
    print(df[col].head(10))

 ============================================================
natural_gas_production_cum
0      225,341,000,000 Cu.M
1       33,170,000,000 Cu.M
2    1,029,000,000,000 Cu.M
3       57,410,000,000 Cu.M
4       36,937,000,000 Cu.M
5       39,951,000,000 Cu.M
6       22,670,000,000 Cu.M
7       24,620,000,000 Cu.M
8      617,830,000,000 Cu.M
9       31,422,000,000 Cu.M
Name: natural_gas_production_cum, dtype: object

 ============================================================
natural_gas_consumption_cum
0    366,160,000,000 Cu.M
1     58,867,000,000 Cu.M
2    914,301,000,000 Cu.M
3     36,061,000,000 Cu.M
4     46,448,000,000 Cu.M
5     20,719,000,000 Cu.M
6     31,654,000,000 Cu.M
7     30,384,000,000 Cu.M
8    472,239,000,000 Cu.M
9     90,566,000,000 Cu.M
Name: natural_gas_consumption_cum, dtype: object

 ============================================================
proven_natural_gas_reserves_cum
0     6,654,000,000,000 Cu.M
1     1,381,000,000,000 Cu.M
2    13,402,000,000,000 Cu.M
3     1,408,000,000,000 Cu.M
4       592,219,000,000 Cu.M
5     5,761,000,000,000 Cu.M
6       363,985,000,000 Cu.M
7       126,293,000,000 Cu.M
8    47,805,000,000,000 Cu.M
9       180,322,000,000 Cu.M
Name: proven_natural_gas_reserves_cum, dtype: object

 ============================================================
coal_production_cum
0    4,805,000,000 Cu.M
1    1,020,000,000 Cu.M
2      534,234,000 Cu.M
3      783,453,000 Cu.M
4       13,765,000 Cu.M
5        1,322,000 Cu.M
6       15,556,000 Cu.M
7          767,000 Cu.M
8      531,130,000 Cu.M
9        6,296,000 Cu.M
Name: coal_production_cum, dtype: object

 ============================================================
proven_coal_reserves_cum
0    157,041,000,000 Cu.M
1    127,727,000,000 Cu.M
2    247,883,000,000 Cu.M
3     35,055,000,000 Cu.M
4      2,857,000,000 Cu.M
5      2,144,000,000 Cu.M
6      6,596,000,000 Cu.M
7      3,260,000,000 Cu.M
8    162,166,000,000 Cu.M
9      1,160,000,000 Cu.M
Name: proven_coal_reserves_cum, dtype: object

In [20]:
gas_cols = [
    "natural_gas_production_cum",
    "natural_gas_consumption_cum",
    "proven_natural_gas_reserves_cum",
    "coal_production_cum",
    "proven_coal_reserves_cum"
]

for col in gas_cols:

    clean_df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("Cu.M", "", regex=False)
        .str.strip()
    )

    clean_df[col] = pd.to_numeric(clean_df[col], errors="coerce")

print("Gas & Coal columns cleaned successfully!")

Gas & Coal columns cleaned successfully!

In [21]:
clean_df[gas_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   natural_gas_production_cum       145 non-null    int64
 1   natural_gas_consumption_cum      145 non-null    int64
 2   proven_natural_gas_reserves_cum  145 non-null    int64
 3   coal_production_cum              145 non-null    int64
 4   proven_coal_reserves_cum         145 non-null    int64
dtypes: int64(5)
memory usage: 5.8 KB

In [22]:
# Check duplicate rows
duplicates = clean_df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [23]:
# Final Missing Values
missing = clean_df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

power_index_score               145
alliance                        115
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
continent                        10
region                           10
dtype: int64

In [24]:
# Save cleaned dataset
clean_df.to_csv("military_cleaned.csv", index=False)

print("military_cleaned.csv saved successfully!")

military_cleaned.csv saved successfully!

In [25]:
print("Final Shape:", clean_df.shape)

print("\nData Types:")
print(clean_df.dtypes)

print("\nFirst 5 Rows:")
display(clean_df.head())

Final Shape: (145, 62)

Data Types:
country_id                   int64
country                     object
total_population             int64
total_military_manpower      int64
fit_for_service              int64
                            ...
power_index_score          float64
continent                   object
region                      object
gdp_usd                    float64
alliance                    object
Length: 62, dtype: object

First 5 Rows:

,country_id,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,power_index_rank,power_index_score,continent,region,gdp_usd,alliance
0,1,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3529,...,9596960,14500,22457,27700,3,NaN,Asia,Eastern Asia,1.800000e+13,NaN
1,2,India,1409128296,662290299,522786598,23955181,1431000,1000000,2527000,2183,...,3287263,7000,13888,14500,4,NaN,Asia,Southern Asia,3.390000e+12,NaN
2,3,United States,341963408,150463900,124816644,4445524,1333030,799500,0,13032,...,9833517,19924,12002,41009,1,NaN,Americas,Northern America,2.550000e+13,NATO
3,4,Indonesia,281562465,137965608,114595923,4786562,404500,401000,250000,460,...,1904569,54716,2958,21579,13,NaN,Asia,South-eastern Asia,1.320000e+12,NaN
4,5,Pakistan,252363571,108516336,85803614,4794908,660000,550000,500000,1397,...,796095,1046,7257,0,14,NaN,Asia,Southern Asia,3.770000e+11,NaN

In [26]:
clean_df[clean_df["continent"].isnull()][["country"]]

                              country
13   Democratic Republic of the Congo
17                            Turkiye
51                        Ivory Coast
55                        North Korea
80                            Czechia
104             Republic of the Congo
121            Bosnia and Herzegovina
133                   North Macedonia
135                            Kosovo
143                             Beliz

In [27]:
clean_df[clean_df["gdp_usd"].isnull()][["country"]]

                              country
8                              Russia
13   Democratic Republic of the Congo
14                              Egypt
16                               Iran
27                        South Korea
47                              Yemen
48                          Venezuela
51                        Ivory Coast
55                        North Korea
56                              Syria
57                             Taiwan
95                               Laos
103                        Kyrgyzstan
104             Republic of the Congo
110                          Slovakia
143                             Beliz

In [28]:
clean_df.to_csv("military_cleaned.csv", index=False)

print("military_cleaned.csv saved successfully!")

military_cleaned.csv saved successfully!

In [5]:
clean_df[clean_df["continent"].isnull()][["country"]]

                              country
13   Democratic Republic of the Congo
17                            Turkiye
51                        Ivory Coast
55                        North Korea
80                            Czechia
104             Republic of the Congo
121            Bosnia and Herzegovina
133                   North Macedonia
135                            Kosovo
143                             Beliz

In [6]:
clean_df[clean_df["gdp_usd"].isnull()][["country"]]

                              country
8                              Russia
13   Democratic Republic of the Congo
14                              Egypt
16                               Iran
27                        South Korea
47                              Yemen
48                          Venezuela
51                        Ivory Coast
55                        North Korea
56                              Syria
57                             Taiwan
95                               Laos
103                        Kyrgyzstan
104             Republic of the Congo
110                          Slovakia
143                             Beliz

In [3]:
import pandas as pd

clean_df = pd.read_csv("military_cleaned.csv")

✅ combined_personnel created

In [ ]:
# ==========================================================
# Combined Personnel
# ==========================================================

clean_df["combined_personnel"] = (
    clean_df["active_personnel"] +
    clean_df["reserve_personnel"] +
    clean_df["paramilitary"]
)

print("✅ combined_personnel created")

In [10]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Features for readiness
readiness_features = [
    "active_personnel",
    "combined_personnel",
    "total_military_manpower"
]

scaler = MinMaxScaler()

scaled = scaler.fit_transform(clean_df[readiness_features])

scaled_df = pd.DataFrame(
    scaled,
    columns=readiness_features,
    index=clean_df.index
)

clean_df["force_readiness_index"] = (
    scaled_df["active_personnel"] * 0.40 +
    scaled_df["combined_personnel"] * 0.30 +
    scaled_df["total_military_manpower"] * 0.30
) * 100

print("✅ force_readiness_index created")

✅ force_readiness_index created

In [8]:
%whos

Variable    Type         Data/Info
----------------------------------
builtins    module       <module 'builtins' (built-in)>
clean_df    DataFrame         country_id        co<...>\n[145 rows x 62 columns]
debugpy     module       <module 'debugpy' from 'c<...>s\\debugpy\\__init__.py'>
ipykernel   module       <module 'ipykernel' from <...>\ipykernel\\__init__.py'>
pd          module       <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>

In [12]:
clean_df[["country", "force_readiness_index"]].head()

         country  force_readiness_index
0          China              83.577955
1          India              75.365727
2  United States              41.240933
3      Indonesia              17.885777
4       Pakistan              24.554963

In [13]:
# ==========================================================
# Air Superiority Index
# ==========================================================

from sklearn.preprocessing import MinMaxScaler
import pandas as pd

air_features = [
    "total_military_aircraft",
    "fighter_aircraft",
    "attack_aircraft",
    "attack_helicopters"
]

scaler = MinMaxScaler()

scaled_air = scaler.fit_transform(clean_df[air_features])

scaled_air_df = pd.DataFrame(
    scaled_air,
    columns=air_features,
    index=clean_df.index
)

clean_df["air_superiority_index"] = (
    scaled_air_df["total_military_aircraft"] * 0.40 +
    scaled_air_df["fighter_aircraft"] * 0.30 +
    scaled_air_df["attack_aircraft"] * 0.20 +
    scaled_air_df["attack_helicopters"] * 0.10
) * 100

print("✅ air_superiority_index created")

✅ air_superiority_index created

In [14]:
clean_df[["country", "air_superiority_index"]].head()

         country  air_superiority_index
0          China              45.759753
1          India              18.123299
2  United States             100.000000
3      Indonesia               2.979502
4       Pakistan              12.313249

In [15]:
# ==========================================================
# Logistics Index
# ==========================================================

from sklearn.preprocessing import MinMaxScaler
import pandas as pd

logistics_features = [
    "total_serviceable_airports",
    "major_ports_and_terminals",
    "railway_coverage_km",
    "roadway_coverage_km"
]

scaler = MinMaxScaler()

scaled_logistics = scaler.fit_transform(clean_df[logistics_features])

scaled_logistics_df = pd.DataFrame(
    scaled_logistics,
    columns=logistics_features,
    index=clean_df.index
)

clean_df["logistics_index"] = (
    scaled_logistics_df["total_serviceable_airports"] * 0.30 +
    scaled_logistics_df["major_ports_and_terminals"] * 0.20 +
    scaled_logistics_df["railway_coverage_km"] * 0.25 +
    scaled_logistics_df["roadway_coverage_km"] * 0.25
) * 100

print("✅ logistics_index created")

✅ logistics_index created

In [16]:
clean_df[["country", "logistics_index"]].head()

         country  logistics_index
0          China        35.515197
1          India        32.031575
2  United States       100.000000
3      Indonesia         7.296937
4       Pakistan         2.310483

In [17]:
# ==========================================================
# Superiority Index
# ==========================================================

clean_df["superiority_index"] = (
    clean_df["force_readiness_index"] * 0.40 +
    clean_df["air_superiority_index"] * 0.30 +
    clean_df["logistics_index"] * 0.30
)

print("✅ superiority_index created")

✅ superiority_index created

In [18]:
clean_df[["country","superiority_index"]].head()

         country  superiority_index
0          China          57.813667
1          India          45.192753
2  United States          76.496373
3      Indonesia          10.237243
4       Pakistan          14.209105

In [19]:
# ==========================================================
# Coalition Score
# ==========================================================

clean_df["coalition_score"] = (
    clean_df.groupby("alliance")["country"]
    .transform("count")
)

clean_df["coalition_score"] = clean_df["coalition_score"].fillna(1)

print("✅ coalition_score created")

✅ coalition_score created

In [20]:
# ==========================================================
# Coalition Budget
# ==========================================================

clean_df["coalition_budget"] = (
    clean_df.groupby("alliance")["defense_budget_usd"]
    .transform("sum")
)

clean_df["coalition_budget"] = clean_df["coalition_budget"].fillna(
    clean_df["defense_budget_usd"]
)

print("✅ coalition_budget created")

✅ coalition_budget created

In [21]:
# ==========================================================
# Power Advantage
# ==========================================================

clean_df["power_advantage"] = (
    clean_df["superiority_index"] -
    clean_df["superiority_index"].mean()
)

print("✅ power_advantage created")

✅ power_advantage created

In [22]:
# ==========================================================
# Budget Advantage
# ==========================================================

clean_df["budget_advantage"] = (
    clean_df["defense_budget_usd"] -
    clean_df["defense_budget_usd"].mean()
)

print("✅ budget_advantage created")

✅ budget_advantage created

In [23]:
# ==========================================================
# Power Index Rank Gap
# ==========================================================

clean_df["power_index_rank_gap"] = (
    clean_df["power_index_rank"] -
    clean_df["power_index_rank"].min()
)

print("✅ power_index_rank_gap created")

✅ power_index_rank_gap created

In [24]:
derived_cols = [
    "combined_personnel",
    "force_readiness_index",
    "air_superiority_index",
    "logistics_index",
    "superiority_index",
    "coalition_score",
    "coalition_budget",
    "power_advantage",
    "budget_advantage",
    "power_index_rank_gap"
]

print(clean_df[derived_cols].head())

   combined_personnel  force_readiness_index  air_superiority_index  \
0             3170000              83.577955              45.759753
1             4958000              75.365727              18.123299
2             2132530              41.240933             100.000000
3             1055500              17.885777               2.979502
4             1710000              24.554963              12.313249

   logistics_index  superiority_index  coalition_score  coalition_budget  \
0        35.515197          57.813667              1.0      3.030000e+11
1        32.031575          45.192753              1.0      1.090000e+11
2       100.000000          76.496373             30.0      1.442072e+12
3         7.296937          10.237243              1.0      1.115530e+10
4         2.310483          14.209105              1.0      9.102115e+09

   power_advantage  budget_advantage  power_index_rank_gap
0        53.379849      2.832681e+11                     2
1        40.758935      8.926810e+10                     3
2        72.062555      8.117681e+11                     0
3         5.803425     -8.576598e+09                    12
4         9.775287     -1.062978e+10                    13

In [25]:
clean_df.to_csv("military_cleaned.csv", index=False)

print("✅ military_cleaned.csv saved successfully!")

✅ military_cleaned.csv saved successfully!

In [26]:
clean_df.isnull().sum().sort_values(ascending=False)

power_index_score               145
alliance                        115
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
continent                        10
                               ...
total_naval_fleet                 0
rocket_projectors                 0
towed_artillery                   0
self_propelled_artillery          0
power_index_rank_gap              0
Length: 72, dtype: int64

In [27]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 72 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country_id                                 145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    int64
 3   total_military_manpower                    145 non-null    int64
 4   fit_for_service                            145 non-null    int64
 5   population_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                           145 non-null    int64
 7   reserve_personnel                          145 non-null    int64
 8   paramilitary                               145 non-null    int64
 9   total_military_aircraft                    145 non-null    int64
 10  fighter_aircraft                           145 non-null    int64
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    int64
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    int64
 17  attack_helicopters                         145 non-null    int64
 18  tanks                                      145 non-null    int64
 19  armored_fighting_vehicles                  145 non-null    int64
 20  self_propelled_artillery                   145 non-null    int64
 21  towed_artillery                            145 non-null    int64
 22  rocket_projectors                          145 non-null    int64
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               51 non-null     float64
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         145 non-null    int64
 34  external_debt_usd                          145 non-null    int64
 35  purchasing_power_parity_usd                145 non-null    int64
 36  foreign_exchange_and_gold_reserves_usd     145 non-null    int64
 37  total_serviceable_airports                 145 non-null    int64
 38  labour_force                               145 non-null    int64
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    int64
 41  railway_coverage_km                        145 non-null    int64
 42  roadway_coverage_km                        145 non-null    int64
 43  oil_production_bbl                         145 non-null    int64
 44  oil_consumption_bbl                        145 non-null    int64
 45  proven_oil_reserves_bbl                    145 non-null    int64
 46  natural_gas_production_cum                 145 non-null    int64
 47  natural_gas_consumption_cum                145 non-null    int64
 48  proven_natural_gas_reserves_cum            145 non-null    int64
 49  coal_production_cum                        145 non-null    int64
 50  coal_consumption_mt                        145 non-null    int64
 51  proven_coal_reserves_cum                   145 non-null    int64
 52  total_land_area_sq_km                      145 non-null    int64
 53  coastline_coverage_km                      145 non-null    int64
 54  border_coverage_km                         145 non-null    int64
 55  waterway_coverage_km                       145 non-null    int64
 56  power_index_rank                           145 non-null    int64
 57  power_index_score                          0 non-null      float64
 58  continent                                  135 non-null    object
 59  region                                     135 non-null    object
 60  gdp_usd                                    129 non-null    float64
 61  alliance                                   30 non-null     object
 62  combined_personnel                         145 non-null    int64
 63  force_readiness_index                      145 non-null    float64
 64  air_superiority_index                      145 non-null    float64
 65  logistics_index                            145 non-null    float64
 66  superiority_index                          145 non-null    float64
 67  coalition_score                            145 non-null    float64
 68  coalition_budget                           145 non-null    float64
 69  power_advantage                            145 non-null    float64
 70  budget_advantage                           145 non-null    float64
 71  power_index_rank_gap                       145 non-null    int64
dtypes: float64(11), int64(57), object(4)
memory usage: 81.7+ KB

In [28]:
clean_df.to_csv("military_cleaned.csv", index=False)

print("Saved Successfully")

Saved Successfully

In [29]:
clean_df[clean_df["continent"].isna()][["country"]]

                              country
13   Democratic Republic of the Congo
17                            Turkiye
51                        Ivory Coast
55                        North Korea
80                            Czechia
104             Republic of the Congo
121            Bosnia and Herzegovina
133                   North Macedonia
135                            Kosovo
143                             Beliz

In [30]:
continents = pd.read_csv("datasets/continents2.csv")
gdp = pd.read_csv("datasets/gdp_data.csv")

print(continents.head())
print(continents.columns)

print(gdp.head())
print(gdp.columns)

             name alpha-2 alpha-3  country-code     iso_3166-2   region  \
0     Afghanistan      AF     AFG             4  ISO 3166-2:AF     Asia
1   Åland Islands      AX     ALA           248  ISO 3166-2:AX   Europe
2         Albania      AL     ALB             8  ISO 3166-2:AL   Europe
3         Algeria      DZ     DZA            12  ISO 3166-2:DZ   Africa
4  American Samoa      AS     ASM            16  ISO 3166-2:AS  Oceania

        sub-region intermediate-region  region-code  sub-region-code  \
0    Southern Asia                 NaN        142.0             34.0
1  Northern Europe                 NaN        150.0            154.0
2  Southern Europe                 NaN        150.0             39.0
3  Northern Africa                 NaN          2.0             15.0
4        Polynesia                 NaN          9.0             61.0

   intermediate-region-code
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
Index(['name', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2', 'region',
       'sub-region', 'intermediate-region', 'region-code', 'sub-region-code',
       'intermediate-region-code'],
      dtype='object')
  country_name country_code  year        value
0  Afghanistan          AFG  1960  537777811.1
1  Afghanistan          AFG  1961  548888895.6
2  Afghanistan          AFG  1962  546666677.8
3  Afghanistan          AFG  1963  751111191.1
4  Afghanistan          AFG  1964  800000044.4
Index(['country_name', 'country_code', 'year', 'value'], dtype='object')

In [31]:
latest_gdp = (
    gdp.sort_values("year")
       .groupby("country_name")
       .last()
       .reset_index()
)

latest_gdp = latest_gdp.rename(columns={
    "country_name": "country",
    "value": "gdp_new"
})

clean_df = clean_df.merge(
    latest_gdp[["country", "gdp_new"]],
    on="country",
    how="left"
)

clean_df["gdp_usd"] = clean_df["gdp_usd"].fillna(clean_df["gdp_new"])

clean_df.drop(columns=["gdp_new"], inplace=True)

In [32]:
clean_df["alliance"] = clean_df["alliance"].fillna("None")

In [33]:
clean_df.isnull().sum().sort_values(ascending=False)

power_index_score               145
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
continent                        10
region                           10
                               ...
total_naval_fleet                 0
rocket_projectors                 0
towed_artillery                   0
self_propelled_artillery          0
power_index_rank_gap              0
Length: 72, dtype: int64

In [36]:
country_mapping = {
    "Turkiye": "Türkiye",
    "Beliz": "Belize",
    "Ivory Coast": "Côte d'Ivoire",
    "North Korea": "Korea (Democratic People's Republic of)",
    "South Korea": "Korea, Republic of",
    "Democratic Republic of the Congo": "Congo, The Democratic Republic of the",
    "Republic of the Congo": "Congo",
    "Russia": "Russian Federation",
    "Iran": "Iran (Islamic Republic of)",
    "Syria": "Syrian Arab Republic",
    "Laos": "Lao People's Democratic Republic",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Egypt": "Egypt, Arab Rep.",
    "Slovakia": "Slovak Republic",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Taiwan": "Taiwan, China",
    "Yemen": "Yemen, Rep."
}

clean_df["country"] = clean_df["country"].replace(country_mapping)

In [37]:
clean_df[clean_df["continent"].isnull()][["country"]]

                                     country
13     Congo, The Democratic Republic of the
17                                   Türkiye
51                             Côte d'Ivoire
55   Korea (Democratic People's Republic of)
80                                   Czechia
104                                    Congo
121                   Bosnia and Herzegovina
133                          North Macedonia
135                                   Kosovo
143                                   Belize

In [38]:
clean_df[clean_df["gdp_usd"].isnull()][["country"]]

                                     country
8                         Russian Federation
13     Congo, The Democratic Republic of the
14                          Egypt, Arab Rep.
16                Iran (Islamic Republic of)
27                        Korea, Republic of
47                               Yemen, Rep.
48        Venezuela (Bolivarian Republic of)
51                             Côte d'Ivoire
55   Korea (Democratic People's Republic of)
56                      Syrian Arab Republic
57                             Taiwan, China
95          Lao People's Democratic Republic
103                          Kyrgyz Republic
104                                    Congo
110                          Slovak Republic
143                                   Belize

In [39]:
clean_df.isnull().sum().sort_values(ascending=False)

power_index_score               145
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
continent                        10
region                           10
                               ...
total_naval_fleet                 0
rocket_projectors                 0
towed_artillery                   0
self_propelled_artillery          0
power_index_rank_gap              0
Length: 72, dtype: int64

In [40]:
continents[continents["name"].str.contains("Tur", case=False, na=False)]

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
227,Turkey,TR,TUR,792,ISO 3166-2:TR,Asia,Western Asia,NaN,142.0,145.0,NaN
228,Turkmenistan,TM,TKM,795,ISO 3166-2:TM,Asia,Central Asia,NaN,142.0,143.0,NaN
229,Turks and Caicos Islands,TC,TCA,796,ISO 3166-2:TC,Americas,Latin America and the Caribbean,Caribbean,19.0,419.0,29.0

In [41]:
gdp[gdp["country_name"].str.contains("Russia|Russian", case=False, na=False)]

             country_name country_code  year         value
10266  Russian Federation          RUS  1988  5.550000e+11
10267  Russian Federation          RUS  1989  5.070000e+11
10268  Russian Federation          RUS  1990  5.170000e+11
10269  Russian Federation          RUS  1991  5.180000e+11
10270  Russian Federation          RUS  1992  4.600000e+11
10271  Russian Federation          RUS  1993  4.350000e+11
10272  Russian Federation          RUS  1994  3.950000e+11
10273  Russian Federation          RUS  1995  3.960000e+11
10274  Russian Federation          RUS  1996  3.920000e+11
10275  Russian Federation          RUS  1997  4.050000e+11
10276  Russian Federation          RUS  1998  2.710000e+11
10277  Russian Federation          RUS  1999  1.960000e+11
10278  Russian Federation          RUS  2000  2.600000e+11
10279  Russian Federation          RUS  2001  3.070000e+11
10280  Russian Federation          RUS  2002  3.450000e+11
10281  Russian Federation          RUS  2003  4.300000e+11
10282  Russian Federation          RUS  2004  5.910000e+11
10283  Russian Federation          RUS  2005  7.640000e+11
10284  Russian Federation          RUS  2006  9.900000e+11
10285  Russian Federation          RUS  2007  1.300000e+12
10286  Russian Federation          RUS  2008  1.660000e+12
10287  Russian Federation          RUS  2009  1.220000e+12
10288  Russian Federation          RUS  2010  1.520000e+12
10289  Russian Federation          RUS  2011  2.050000e+12
10290  Russian Federation          RUS  2012  2.210000e+12
10291  Russian Federation          RUS  2013  2.290000e+12
10292  Russian Federation          RUS  2014  2.060000e+12
10293  Russian Federation          RUS  2015  1.360000e+12
10294  Russian Federation          RUS  2016  1.280000e+12
10295  Russian Federation          RUS  2017  1.570000e+12
10296  Russian Federation          RUS  2018  1.660000e+12
10297  Russian Federation          RUS  2019  1.690000e+12
10298  Russian Federation          RUS  2020  1.490000e+12
10299  Russian Federation          RUS  2021  1.840000e+12
10300  Russian Federation          RUS  2022  2.240000e+12

In [42]:
clean_df.columns

Index(['country_id', 'country', 'total_population', 'total_military_manpower',
       'fit_for_service', 'population_reaching_military_age_annually',
       'active_personnel', 'reserve_personnel', 'paramilitary',
       'total_military_aircraft', 'fighter_aircraft', 'attack_aircraft',
       'transport_aircraft', 'trainer_aircraft', 'special_mission_aircraft',
       'tanker_aircraft', 'total_military_helicopters', 'attack_helicopters',
       'tanks', 'armored_fighting_vehicles', 'self_propelled_artillery',
       'towed_artillery', 'rocket_projectors', 'total_naval_fleet',
       'total_naval_fleet_tonnage_mt', 'aircraft_carriers',
       'helicopter_carriers', 'submarines', 'destroyers', 'frigates',
       'corvettes', 'coastal_patrol_craft', 'mine_warfare_craft',
       'defense_budget_usd', 'external_debt_usd',
       'purchasing_power_parity_usd', 'foreign_exchange_and_gold_reserves_usd',
       'total_serviceable_airports', 'labour_force',
       'major_ports_and_terminals', 'total_merchant_marine_fleet',
       'railway_coverage_km', 'roadway_coverage_km', 'oil_production_bbl',
       'oil_consumption_bbl', 'proven_oil_reserves_bbl',
       'natural_gas_production_cum', 'natural_gas_consumption_cum',
       'proven_natural_gas_reserves_cum', 'coal_production_cum',
       'coal_consumption_mt', 'proven_coal_reserves_cum',
       'total_land_area_sq_km', 'coastline_coverage_km', 'border_coverage_km',
       'waterway_coverage_km', 'power_index_rank', 'power_index_score',
       'continent', 'region', 'gdp_usd', 'alliance', 'combined_personnel',
       'force_readiness_index', 'air_superiority_index', 'logistics_index',
       'superiority_index', 'coalition_score', 'coalition_budget',
       'power_advantage', 'budget_advantage', 'power_index_rank_gap'],
      dtype='object')

In [43]:
clean_df.isnull().sum().sort_values(ascending=False)

power_index_score               145
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
continent                        10
region                           10
                               ...
total_naval_fleet                 0
rocket_projectors                 0
towed_artillery                   0
self_propelled_artillery          0
power_index_rank_gap              0
Length: 72, dtype: int64

In [44]:
clean_df[clean_df["continent"].isnull()][["country"]]

                                     country
13     Congo, The Democratic Republic of the
17                                   Türkiye
51                             Côte d'Ivoire
55   Korea (Democratic People's Republic of)
80                                   Czechia
104                                    Congo
121                   Bosnia and Herzegovina
133                          North Macedonia
135                                   Kosovo
143                                   Belize

In [45]:
clean_df[clean_df["gdp_usd"].isnull()][["country"]]

                                     country
8                         Russian Federation
13     Congo, The Democratic Republic of the
14                          Egypt, Arab Rep.
16                Iran (Islamic Republic of)
27                        Korea, Republic of
47                               Yemen, Rep.
48        Venezuela (Bolivarian Republic of)
51                             Côte d'Ivoire
55   Korea (Democratic People's Republic of)
56                      Syrian Arab Republic
57                             Taiwan, China
95          Lao People's Democratic Republic
103                          Kyrgyz Republic
104                                    Congo
110                          Slovak Republic
143                                   Belize

In [46]:
clean_df.loc[clean_df["country"]=="Türkiye", ["continent","region"]] = ["Asia","Western Asia"]

clean_df.loc[clean_df["country"]=="Congo, The Democratic Republic of the", ["continent","region"]] = ["Africa","Middle Africa"]

clean_df.loc[clean_df["country"]=="Congo", ["continent","region"]] = ["Africa","Middle Africa"]

clean_df.loc[clean_df["country"]=="Côte d'Ivoire", ["continent","region"]] = ["Africa","Western Africa"]

clean_df.loc[clean_df["country"]=="Korea (Democratic People's Republic of)", ["continent","region"]] = ["Asia","Eastern Asia"]

clean_df.loc[clean_df["country"]=="Czechia", ["continent","region"]] = ["Europe","Eastern Europe"]

clean_df.loc[clean_df["country"]=="Bosnia and Herzegovina", ["continent","region"]] = ["Europe","Southern Europe"]

clean_df.loc[clean_df["country"]=="North Macedonia", ["continent","region"]] = ["Europe","Southern Europe"]

clean_df.loc[clean_df["country"]=="Kosovo", ["continent","region"]] = ["Europe","Southern Europe"]

clean_df.loc[clean_df["country"]=="Belize", ["continent","region"]] = ["Americas","Central America"]

print("Continent & Region completed.")

Continent & Region completed.

In [47]:
clean_df[clean_df["continent"].isnull()][["country"]]

Empty DataFrame
Columns: [country]
Index: []

In [48]:
clean_df["continent"].isnull().sum()

0

In [49]:
clean_df["region"].isnull().sum()

0

In [50]:
clean_df["gdp_usd"].isnull().sum()

16

In [51]:
clean_df.isnull().sum().sort_values(ascending=False)

power_index_score               145
total_naval_fleet_tonnage_mt     94
gdp_usd                          16
country_id                        0
natural_gas_consumption_cum       0
                               ...
total_naval_fleet                 0
rocket_projectors                 0
towed_artillery                   0
self_propelled_artillery          0
power_index_rank_gap              0
Length: 72, dtype: int64

In [52]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 72 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country_id                                 145 non-null    int64
 1   country                                    145 non-null    object
 2   total_population                           145 non-null    int64
 3   total_military_manpower                    145 non-null    int64
 4   fit_for_service                            145 non-null    int64
 5   population_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                           145 non-null    int64
 7   reserve_personnel                          145 non-null    int64
 8   paramilitary                               145 non-null    int64
 9   total_military_aircraft                    145 non-null    int64
 10  fighter_aircraft                           145 non-null    int64
 11  attack_aircraft                            145 non-null    int64
 12  transport_aircraft                         145 non-null    int64
 13  trainer_aircraft                           145 non-null    int64
 14  special_mission_aircraft                   145 non-null    int64
 15  tanker_aircraft                            145 non-null    int64
 16  total_military_helicopters                 145 non-null    int64
 17  attack_helicopters                         145 non-null    int64
 18  tanks                                      145 non-null    int64
 19  armored_fighting_vehicles                  145 non-null    int64
 20  self_propelled_artillery                   145 non-null    int64
 21  towed_artillery                            145 non-null    int64
 22  rocket_projectors                          145 non-null    int64
 23  total_naval_fleet                          145 non-null    int64
 24  total_naval_fleet_tonnage_mt               51 non-null     float64
 25  aircraft_carriers                          145 non-null    int64
 26  helicopter_carriers                        145 non-null    int64
 27  submarines                                 145 non-null    int64
 28  destroyers                                 145 non-null    int64
 29  frigates                                   145 non-null    int64
 30  corvettes                                  145 non-null    int64
 31  coastal_patrol_craft                       145 non-null    int64
 32  mine_warfare_craft                         145 non-null    int64
 33  defense_budget_usd                         145 non-null    int64
 34  external_debt_usd                          145 non-null    int64
 35  purchasing_power_parity_usd                145 non-null    int64
 36  foreign_exchange_and_gold_reserves_usd     145 non-null    int64
 37  total_serviceable_airports                 145 non-null    int64
 38  labour_force                               145 non-null    int64
 39  major_ports_and_terminals                  145 non-null    int64
 40  total_merchant_marine_fleet                145 non-null    int64
 41  railway_coverage_km                        145 non-null    int64
 42  roadway_coverage_km                        145 non-null    int64
 43  oil_production_bbl                         145 non-null    int64
 44  oil_consumption_bbl                        145 non-null    int64
 45  proven_oil_reserves_bbl                    145 non-null    int64
 46  natural_gas_production_cum                 145 non-null    int64
 47  natural_gas_consumption_cum                145 non-null    int64
 48  proven_natural_gas_reserves_cum            145 non-null    int64
 49  coal_production_cum                        145 non-null    int64
 50  coal_consumption_mt                        145 non-null    int64
 51  proven_coal_reserves_cum                   145 non-null    int64
 52  total_land_area_sq_km                      145 non-null    int64
 53  coastline_coverage_km                      145 non-null    int64
 54  border_coverage_km                         145 non-null    int64
 55  waterway_coverage_km                       145 non-null    int64
 56  power_index_rank                           145 non-null    int64
 57  power_index_score                          0 non-null      float64
 58  continent                                  145 non-null    object
 59  region                                     145 non-null    object
 60  gdp_usd                                    129 non-null    float64
 61  alliance                                   145 non-null    object
 62  combined_personnel                         145 non-null    int64
 63  force_readiness_index                      145 non-null    float64
 64  air_superiority_index                      145 non-null    float64
 65  logistics_index                            145 non-null    float64
 66  superiority_index                          145 non-null    float64
 67  coalition_score                            145 non-null    float64
 68  coalition_budget                           145 non-null    float64
 69  power_advantage                            145 non-null    float64
 70  budget_advantage                           145 non-null    float64
 71  power_index_rank_gap                       145 non-null    int64
dtypes: float64(11), int64(57), object(4)
memory usage: 81.7+ KB

In [53]:
clean_df.to_csv("military_cleaned.csv", index=False)

print("military_cleaned.csv saved successfully!")

military_cleaned.csv saved successfully!