In [9]:
import pandas as pd
import re

print("Notebook is working successfully!")

Notebook is working successfully!

In [10]:
# Load the dataset
df = pd.read_csv("military_raw_data.csv")

# Display first 5 rows
df.head()

,Metric,Rank,Country,Value,Source_URL
0,2026 Military Strength Ranking,1,United States,NaN,https://www.globalfirepower.com/countries-list...
1,2026 Military Strength Ranking,2,Russia,NaN,https://www.globalfirepower.com/countries-list...
2,2026 Military Strength Ranking,3,China,NaN,https://www.globalfirepower.com/countries-list...
3,2026 Military Strength Ranking,4,India,NaN,https://www.globalfirepower.com/countries-list...
4,2026 Military Strength Ranking,5,South Korea,NaN,https://www.globalfirepower.com/countries-list...

# Military Data Cleaning and Structuring

## Objective
This notebook performs the following tasks:

- Load the raw military dataset
- Standardize column names
- Clean text values
- Convert metrics to numeric format
- Handle missing values
- Remove duplicate rows
- Save the cleaned dataset

In [11]:
print("Shape of Dataset:", df.shape)
print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

Shape of Dataset: (7881, 5)

Column Names:
Index(['Metric', 'Rank', 'Country', 'Value', 'Source_URL'], dtype='object')

Missing Values:
Metric          0
Rank            0
Country         0
Value         145
Source_URL      0
dtype: int64

In [12]:
# Standardize column names

df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
      .str.replace("-", "_", regex=False)
      .str.replace("/", "_", regex=False)
)

print(df.columns)

Index(['metric', 'rank', 'country', 'value', 'source_url'], dtype='object')

In [13]:
# Function to clean text values

def clean_text(value):

    if pd.isna(value):
        return None

    value = str(value).strip()

    value = value.replace(",", "")
    value = value.replace("%", "")
    value = value.replace("+", "")
    value = value.replace("$", "")

    value = re.sub(r"[\(\)\[\]]", "", value)

    value = re.sub(r"\s+", " ", value)

    return value

for col in df.columns:
    if df[col].dtype == object:
        df[col] = df[col].apply(clean_text)

print("Text cleaning completed.")

Text cleaning completed.

In [14]:
# Convert rank to numeric

df["rank"] = pd.to_numeric(df["rank"], errors="coerce")

print(df.dtypes)

metric        object
rank           int64
country       object
value         object
source_url    object
dtype: object

In [15]:
# Handle missing values

numeric_columns = df.select_dtypes(include=["number"]).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

text_columns = df.select_dtypes(include=["object"]).columns

for col in text_columns:
    df[col] = df[col].fillna("Unknown")

print(df.isnull().sum())

metric        0
rank          0
country       0
value         0
source_url    0
dtype: int64

In [16]:
# Remove duplicate rows

before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Duplicates Removed:", before - after)

Duplicates Removed: 0

In [17]:
# Save cleaned dataset

df.to_csv("military_cleaned.csv", index=False)

print("military_cleaned.csv created successfully!")

military_cleaned.csv created successfully!

In [18]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

missing = (
    df.isnull().sum().sum()
    /
    (df.shape[0] * df.shape[1])
) * 100

print("Missing Percentage:", round(missing, 2), "%")

df.head()

Rows : 7881
Columns : 5
Missing Percentage: 0.0 %

,metric,rank,country,value,source_url
0,2026 Military Strength Ranking,1,United States,Unknown,https://www.globalfirepower.com/countries-list...
1,2026 Military Strength Ranking,2,Russia,Unknown,https://www.globalfirepower.com/countries-list...
2,2026 Military Strength Ranking,3,China,Unknown,https://www.globalfirepower.com/countries-list...
3,2026 Military Strength Ranking,4,India,Unknown,https://www.globalfirepower.com/countries-list...
4,2026 Military Strength Ranking,5,South Korea,Unknown,https://www.globalfirepower.com/countries-list...