#####     Module 2: Data Cleaning and Structuring      ######

In [8]:
import pandas as pd
import numpy as np
import re

In [9]:
print("Notebook is working!")
print(pd.__version__)

Notebook is working!
3.0.2

In [10]:
df = pd.read_csv("C:\\Users\\hirai\\Desktop\\Unified-Military-Analytics\\Module1\\military_raw_data.csv")
print(df.shape)
df.head()

(145, 61)

,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,fighter_aircraft,...,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,continent,region,gdp_usd,nato_member,power_index_rank,power_index_score
0,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,529","1,443",...,"9,596,960 km","14,500 km","22,457 km","27,700 km",Asia,Eastern Asia,1.800000e+13,No,3,0.0919
1,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,431,000","1,000,000","2,527,000","2,183",476,...,"3,287,263 km","7,000 km","13,888 km","14,500 km",Asia,Southern Asia,3.390000e+12,No,4,0.1346
2,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,333,030","799,500",0,"13,032","1,791",...,"9,833,517 km","19,924 km","12,002 km","41,009 km",Americas,Northern America,2.550000e+13,Yes,1,0.0741
3,Indonesia,"281,562,465","137,965,608","114,595,923","4,786,562","404,500","401,000","250,000",460,41,...,"1,904,569 km","54,716 km","2,958 km","21,579 km",Asia,South-eastern Asia,1.320000e+12,No,13,0.2582
4,Pakistan,"252,363,571","108,516,336","85,803,614","4,794,908","660,000","550,000","500,000","1,397",331,...,"796,095 km","1,046 km","7,257 km",0 km,Asia,Southern Asia,3.770000e+11,No,14,0.2626

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 61 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    145 non-null    str
 1   total_population                           145 non-null    str
 2   total_military_manpower                    145 non-null    str
 3   fit_for_service                            145 non-null    str
 4   population_reaching_military_age_annually  145 non-null    str
 5   active_personnel                           145 non-null    str
 6   reserve_personnel                          145 non-null    str
 7   paramilitary                               145 non-null    str
 8   total_military_aircraft                    145 non-null    str
 9   fighter_aircraft                           145 non-null    str
 10  attack_aircraft                            145 non-null    int64
 11  transport_aircraft                         145 non-null    int64
 12  trainer_aircraft                           145 non-null    str
 13  special_mission_aircraft                   145 non-null    int64
 14  tanker_aircraft                            145 non-null    int64
 15  total_military_helicopters                 145 non-null    str
 16  attack_helicopters                         145 non-null    str
 17  tanks                                      145 non-null    str
 18  armored_fighting_vehicles                  145 non-null    str
 19  self_propelled_artillery                   145 non-null    str
 20  towed_artillery                            145 non-null    str
 21  rocket_projectors                          145 non-null    str
 22  total_naval_fleet                          145 non-null    int64
 23  total_naval_fleet_tonnage_mt               51 non-null     str
 24  aircraft_carriers                          145 non-null    int64
 25  helicopter_carriers                        145 non-null    int64
 26  submarines                                 145 non-null    int64
 27  destroyers                                 145 non-null    int64
 28  frigates                                   145 non-null    int64
 29  corvettes                                  145 non-null    int64
 30  coastal_patrol_craft                       145 non-null    int64
 31  mine_warfare_craft                         145 non-null    int64
 32  defense_budget_usd                         145 non-null    str
 33  external_debt_usd                          145 non-null    str
 34  purchasing_power_parity_usd                145 non-null    str
 35  foreign_exchange_and_gold_reserves_usd     145 non-null    str
 36  total_serviceable_airports                 145 non-null    str
 37  labour_force                               145 non-null    str
 38  major_ports_and_terminals                  145 non-null    int64
 39  total_merchant_marine_fleet                145 non-null    str
 40  railway_coverage_km                        145 non-null    str
 41  roadway_coverage_km                        145 non-null    str
 42  oil_production_bbl                         145 non-null    str
 43  oil_consumption_bbl                        145 non-null    str
 44  proven_oil_reserves_bbl                    145 non-null    str
 45  natural_gas_production_cum                 145 non-null    str
 46  natural_gas_consumption_cum                145 non-null    str
 47  proven_natural_gas_reserves_cum            145 non-null    str
 48  coal_production_cum                        145 non-null    str
 49  coal_consumption_mt                        145 non-null    str
 50  proven_coal_reserves_cum                   145 non-null    str
 51  total_land_area_sq_km                      145 non-null    str
 52  coastline_coverage_km                      145 non-null    str
 53  border_coverage_km                         145 non-null    str
 54  waterway_coverage_km                       145 non-null    str
 55  continent                                  145 non-null    str
 56  region                                     145 non-null    str
 57  gdp_usd                                    143 non-null    float64
 58  nato_member                                145 non-null    str
 59  power_index_rank                           145 non-null    int64
 60  power_index_score                          145 non-null    float64
dtypes: float64(2), int64(15), str(44)
memory usage: 117.7 KB

In [13]:
# 1. Cleaning the Text
def clean_text(value):
    if pd.isna(value):
        return value
    value = str(value)
    # Remove commas
    value = value.replace(",", "")
    # Remove symbols and units
    remove_items = ["%", "+", "$", "sq km", "km", "bbl", "Cu.M", "mt", "USD"]
    for item in remove_items:
        value = value.replace(item, "")
    return value.strip()

In [14]:
text_cols = df.select_dtypes(include=["object", "string"]).columns
for col in text_cols:
    df[col] = df[col].apply(clean_text)
print(df)

           country total_population total_military_manpower fit_for_service  \
0            China       1415043270               764123366       626864169
1            India       1409128296               662290299       522786598
2    United States        341963408               150463900       124816644
3        Indonesia        281562465               137965608       114595923
4         Pakistan        252363571               108516336        85803614
..             ...              ...                     ...             ...
140     Luxembourg           671254                  154388           92633
141       Suriname           646758                  142287           84079
142     Montenegro           599849                  143964           85179
143         Belize           415789                  158000           90226
144        Iceland           364036                   83728           50237

    population_reaching_military_age_annually active_personnel  \
0                                    19810606          2035000
1                                    23955181          1431000
2                                     4445524          1333030
3                                     4786562           404500
4                                     4794908           660000
..                                        ...              ...
140                                      3356             1200
141                                      3234             2500
142                                      3599             2350
143                                      8732             2000
144                                      1820                0

    reserve_personnel paramilitary total_military_aircraft fighter_aircraft  \
0              510000       625000                    3529             1443
1             1000000      2527000                    2183              476
2              799500            0                   13032             1791
3              401000       250000                     460               41
4              550000       500000                    1397              331
..                ...          ...                     ...              ...
140                 0            0                       1                0
141                 0          200                       3                0
142                 0         5500                      10                0
143               850            0                       3                0
144                 0            0                       0                0

     ...  total_land_area_sq_km  coastline_coverage_km border_coverage_km  \
0    ...                9596960                  14500              22457
1    ...                3287263                   7000              13888
2    ...                9833517                  19924              12002
3    ...                1904569                  54716               2958
4    ...                 796095                   1046               7257
..   ...                    ...                    ...                ...
140  ...                   2586                      0                327
141  ...                 163820                    386               1907
142  ...                  13812                    294                680
143  ...                  22966                    386                542
144  ...                 100250                   4970                  0

     waterway_coverage_km  continent                           region  \
0                   27700       Asia                     Eastern Asia
1                   14500       Asia                    Southern Asia
2                   41009   Americas                 Northern America
3                   21579       Asia               South-eastern Asia
4                       0       Asia                    Southern Asia
..                    ...        ...                              ...
140                    37     Europe                   Western Europe
141                  1200   Americas  Latin America and the Caribbean
142                     0     Europe                  Southern Europe
143                   825   Americas  Latin America and the Caribbean
144                     0     Europe                  Northern Europe

          gdp_usd nato_member power_index_rank power_index_score
0    1.800000e+13          No                3            0.0919
1    3.390000e+12          No                4            0.1346
2    2.550000e+13         Yes                1            0.0741
3    1.320000e+12          No               13            0.2582
4    3.770000e+11          No               14            0.2626
..            ...         ...              ...               ...
140  8.227481e+10         Yes              110            2.4429
141  3.620655e+09          No              142            4.0538
142  6.095979e+09         Yes              128            2.9782
143  2.824082e+09          No              144            4.3602
144  2.784165e+10         Yes              134            3.4013

[145 rows x 61 columns]

In [15]:
#2. Convert metrics to numeric formats
text_columns = ["country", "continent", "region", "nato_member"]
for col in df.columns:
    if col not in text_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
df.head()

,country,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,fighter_aircraft,...,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,continent,region,gdp_usd,nato_member,power_index_rank,power_index_score
0,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3529,1443,...,9596960,14500,22457,27700,Asia,Eastern Asia,1.800000e+13,No,3,0.0919
1,India,1409128296,662290299,522786598,23955181,1431000,1000000,2527000,2183,476,...,3287263,7000,13888,14500,Asia,Southern Asia,3.390000e+12,No,4,0.1346
2,United States,341963408,150463900,124816644,4445524,1333030,799500,0,13032,1791,...,9833517,19924,12002,41009,Americas,Northern America,2.550000e+13,Yes,1,0.0741
3,Indonesia,281562465,137965608,114595923,4786562,404500,401000,250000,460,41,...,1904569,54716,2958,21579,Asia,South-eastern Asia,1.320000e+12,No,13,0.2582
4,Pakistan,252363571,108516336,85803614,4794908,660000,550000,500000,1397,331,...,796095,1046,7257,0,Asia,Southern Asia,3.770000e+11,No,14,0.2626

In [16]:
df[["country", "continent", "region", "nato_member"]].head()

         country continent              region nato_member
0          China      Asia        Eastern Asia          No
1          India      Asia       Southern Asia          No
2  United States  Americas    Northern America         Yes
3      Indonesia      Asia  South-eastern Asia          No
4       Pakistan      Asia       Southern Asia          No

In [17]:
df.dtypes

country                                          str
total_population                               int64
total_military_manpower                        int64
fit_for_service                                int64
population_reaching_military_age_annually      int64
                                              ...
region                                           str
gdp_usd                                      float64
nato_member                                      str
power_index_rank                               int64
power_index_score                            float64
Length: 61, dtype: object

In [18]:
# 3. Standardize column names
df.rename(columns={
    "total_military_manpower": "military_manpower",
    "total_military_aircraft": "total_aircraft",
    "total_military_helicopters": "total_helicopters",
    "total_naval_fleet_tonnage_mt": "naval_fleet_tonnage",
    "total_land_area_sq_km": "land_area_sq_km",
    "total_serviceable_airports": "serviceable_airports",
    "total_merchant_marine_fleet": "merchant_marine_fleet",
    "gdp_usd": "gdp"
}, inplace=True)

In [19]:
# 4. Handle missing/null values

In [21]:
df.isnull().sum()

country                                      0
total_population                             0
military_manpower                            0
fit_for_service                              0
population_reaching_military_age_annually    0
                                            ..
region                                       0
gdp                                          2
nato_member                                  0
power_index_rank                             0
power_index_score                            0
Length: 61, dtype: int64

In [22]:
print(df[["continent", "region"]].isnull().sum())

continent    0
region       0
dtype: int64

In [23]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

naval_fleet_tonnage    94
gdp                     2
dtype: int64

In [24]:
#Cleaning naval_fleet_tonnage  column
df[df["naval_fleet_tonnage"].isnull()][
    ["country", "total_naval_fleet"]].head(10)

                               country  total_naval_fleet
9                               Mexico                164
11                            Ethiopia                  0
13  Congo (Democratic Republic Of The)                 16
22                            Tanzania                 12
25                               Kenya                 27
28                               Sudan                 10
30                              Uganda                  0
35                         Afghanistan                  0
38                             Morocco                100
39                              Angola                 32

In [25]:
df.loc[(df["total_naval_fleet"] == 0) &
    (df["naval_fleet_tonnage"].isna()),
    "naval_fleet_tonnage"] = 0
print(df["naval_fleet_tonnage"].isnull().sum())

63

In [26]:
df.drop(columns=["naval_fleet_tonnage"], inplace=True)

In [27]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

gdp    2
dtype: int64

In [28]:
#Cleaning  gdp column
df[df["gdp"].isnull()][["country"]]

        country
55  North Korea
57       Taiwan

In [29]:
print(df.columns.tolist())

['country', 'total_population', 'military_manpower', 'fit_for_service', 'population_reaching_military_age_annually', 'active_personnel', 'reserve_personnel', 'paramilitary', 'total_aircraft', 'fighter_aircraft', 'attack_aircraft', 'transport_aircraft', 'trainer_aircraft', 'special_mission_aircraft', 'tanker_aircraft', 'total_helicopters', 'attack_helicopters', 'tanks', 'armored_fighting_vehicles', 'self_propelled_artillery', 'towed_artillery', 'rocket_projectors', 'total_naval_fleet', 'aircraft_carriers', 'helicopter_carriers', 'submarines', 'destroyers', 'frigates', 'corvettes', 'coastal_patrol_craft', 'mine_warfare_craft', 'defense_budget_usd', 'external_debt_usd', 'purchasing_power_parity_usd', 'foreign_exchange_and_gold_reserves_usd', 'serviceable_airports', 'labour_force', 'major_ports_and_terminals', 'merchant_marine_fleet', 'railway_coverage_km', 'roadway_coverage_km', 'oil_production_bbl', 'oil_consumption_bbl', 'proven_oil_reserves_bbl', 'natural_gas_production_cum', 'natural_gas_consumption_cum', 'proven_natural_gas_reserves_cum', 'coal_production_cum', 'coal_consumption_mt', 'proven_coal_reserves_cum', 'land_area_sq_km', 'coastline_coverage_km', 'border_coverage_km', 'waterway_coverage_km', 'continent', 'region', 'gdp', 'nato_member', 'power_index_rank', 'power_index_score']

In [30]:
print("Duplicate countries:", df["country"].duplicated().sum())

Duplicate countries: 0

In [31]:
df.head()

,country,total_population,military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_aircraft,fighter_aircraft,...,land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,continent,region,gdp,nato_member,power_index_rank,power_index_score
0,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3529,1443,...,9596960,14500,22457,27700,Asia,Eastern Asia,1.800000e+13,No,3,0.0919
1,India,1409128296,662290299,522786598,23955181,1431000,1000000,2527000,2183,476,...,3287263,7000,13888,14500,Asia,Southern Asia,3.390000e+12,No,4,0.1346
2,United States,341963408,150463900,124816644,4445524,1333030,799500,0,13032,1791,...,9833517,19924,12002,41009,Americas,Northern America,2.550000e+13,Yes,1,0.0741
3,Indonesia,281562465,137965608,114595923,4786562,404500,401000,250000,460,41,...,1904569,54716,2958,21579,Asia,South-eastern Asia,1.320000e+12,No,13,0.2582
4,Pakistan,252363571,108516336,85803614,4794908,660000,550000,500000,1397,331,...,796095,1046,7257,0,Asia,Southern Asia,3.770000e+11,No,14,0.2626

In [32]:
df.tail()

,country,total_population,military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_aircraft,fighter_aircraft,...,land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,continent,region,gdp,nato_member,power_index_rank,power_index_score
140,Luxembourg,671254,154388,92633,3356,1200,0,0,1,0,...,2586,0,327,37,Europe,Western Europe,8.227481e+10,Yes,110,2.4429
141,Suriname,646758,142287,84079,3234,2500,0,200,3,0,...,163820,386,1907,1200,Americas,Latin America and the Caribbean,3.620655e+09,No,142,4.0538
142,Montenegro,599849,143964,85179,3599,2350,0,5500,10,0,...,13812,294,680,0,Europe,Southern Europe,6.095979e+09,Yes,128,2.9782
143,Belize,415789,158000,90226,8732,2000,850,0,3,0,...,22966,386,542,825,Americas,Latin America and the Caribbean,2.824082e+09,No,144,4.3602
144,Iceland,364036,83728,50237,1820,0,0,0,0,0,...,100250,4970,0,0,Europe,Northern Europe,2.784165e+10,Yes,134,3.4013

In [33]:
print(df)

           country  total_population  military_manpower  fit_for_service  \
0            China        1415043270          764123366        626864169
1            India        1409128296          662290299        522786598
2    United States         341963408          150463900        124816644
3        Indonesia         281562465          137965608        114595923
4         Pakistan         252363571          108516336         85803614
..             ...               ...                ...              ...
140     Luxembourg            671254             154388            92633
141       Suriname            646758             142287            84079
142     Montenegro            599849             143964            85179
143         Belize            415789             158000            90226
144        Iceland            364036              83728            50237

     population_reaching_military_age_annually  active_personnel  \
0                                     19810606           2035000
1                                     23955181           1431000
2                                      4445524           1333030
3                                      4786562            404500
4                                      4794908            660000
..                                         ...               ...
140                                       3356              1200
141                                       3234              2500
142                                       3599              2350
143                                       8732              2000
144                                       1820                 0

     reserve_personnel  paramilitary  total_aircraft  fighter_aircraft  ...  \
0               510000        625000            3529              1443  ...
1              1000000       2527000            2183               476  ...
2               799500             0           13032              1791  ...
3               401000        250000             460                41  ...
4               550000        500000            1397               331  ...
..                 ...           ...             ...               ...  ...
140                  0             0               1                 0  ...
141                  0           200               3                 0  ...
142                  0          5500              10                 0  ...
143                850             0               3                 0  ...
144                  0             0               0                 0  ...

     land_area_sq_km  coastline_coverage_km  border_coverage_km  \
0            9596960                  14500               22457
1            3287263                   7000               13888
2            9833517                  19924               12002
3            1904569                  54716                2958
4             796095                   1046                7257
..               ...                    ...                 ...
140             2586                      0                 327
141           163820                    386                1907
142            13812                    294                 680
143            22966                    386                 542
144           100250                   4970                   0

     waterway_coverage_km  continent                           region  \
0                   27700       Asia                     Eastern Asia
1                   14500       Asia                    Southern Asia
2                   41009   Americas                 Northern America
3                   21579       Asia               South-eastern Asia
4                       0       Asia                    Southern Asia
..                    ...        ...                              ...
140                    37     Europe                   Western Europe
141                  1200   Americas  Latin America and the Caribbean
142                     0     Europe                  Southern Europe
143                   825   Americas  Latin America and the Caribbean
144                     0     Europe                  Northern Europe

              gdp  nato_member  power_index_rank  power_index_score
0    1.800000e+13           No                 3             0.0919
1    3.390000e+12           No                 4             0.1346
2    2.550000e+13          Yes                 1             0.0741
3    1.320000e+12           No                13             0.2582
4    3.770000e+11           No                14             0.2626
..            ...          ...               ...                ...
140  8.227481e+10          Yes               110             2.4429
141  3.620655e+09           No               142             4.0538
142  6.095979e+09          Yes               128             2.9782
143  2.824082e+09           No               144             4.3602
144  2.784165e+10          Yes               134             3.4013

[145 rows x 60 columns]

In [35]:
df.to_csv("military_cleaned.csv", index=False, encoding="utf-8")
print("military_cleaned.csv created successfully.")

military_cleaned.csv created successfully.